# Generated by Django 6.0.1 on 2026-01-10 08:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for this placement (e.g., header_banner, sidebar_top)', max_length=100, unique=True, verbose_name='Placement Name')),
                ('description', models.TextField(blank=True, help_text='Description of where this placement appears', verbose_name='Description')),
                ('template_tag', models.CharField(help_text='Template tag name to use (e.g., show_ads header_banner)', max_length=100, verbose_name='Template Tag')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Placement',
                'verbose_name_plural': 'Ad Placements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this ad unit', max_length=200, verbose_name='Ad Unit Name')),
                ('ad_client', models.CharField(help_text='Your Google AdSense Publisher ID (e.g., ca-pub-1234567890123456)', max_length=100, verbose_name='Ad Client ID')),
                ('ad_slot', models.CharField(blank=True, help_text='AdSense Ad Slot ID (e.g., 1234567890)', max_length=50, verbose_name='Ad Slot ID')),
                ('ad_format', models.CharField(blank=True, help_text='Ad format code from AdSense', max_length=50, verbose_name='Ad Format')),
                ('ad_type', models.CharField(choices=[('display', 'Display Ad'), ('in_article', 'In-Article Ad'), ('in_feed', 'In-Feed Ad'), ('matched_content', 'Matched Content'), ('anchor', 'Anchor Ad'), ('vignette', 'Vignette Ad')], default='display', max_length=20, verbose_name='Ad Type')),
                ('ad_size', models.CharField(choices=[('auto', 'Auto'), ('responsive', 'Responsive'), ('rectangle', 'Rectangle (300x250)'), ('large_rectangle', 'Large Rectangle (336x280)'), ('leaderboard', 'Leaderboard (728x90)'), ('banner', 'Banner (468x60)'), ('half_banner', 'Half Banner (234x60)'), ('skyscraper', 'Skyscraper (120x600)'), ('wide_skyscraper', 'Wide Skyscraper (160x600)'), ('square', 'Square (250x250)'), ('small_square', 'Small Square (200x200)'), ('mobile_banner', 'Mobile Banner (320x50)')], default='auto', max_length=20, verbose_name='Ad Size')),
                ('placement', models.CharField(choices=[('header', 'Header'), ('sidebar', 'Sidebar'), ('footer', 'Footer'), ('content_top', 'Content Top'), ('content_middle', 'Content Middle'), ('content_bottom', 'Content Bottom'), ('before_post', 'Before Post'), ('after_post', 'After Post'), ('between_posts', 'Between Posts'), ('sticky', 'Sticky'), ('custom', 'Custom')], max_length=30, verbose_name='Placement Location')),
                ('custom_placement', models.CharField(blank=True, help_text='If placement is "custom", specify the name', max_length=100, verbose_name='Custom Placement Name')),
                ('ad_code', models.TextField(help_text='Paste your complete AdSense ad code here', verbose_name='Ad Code')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this ad unit', verbose_name='Active')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority ads show first (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Priority')),
                ('show_on_homepage', models.BooleanField(default=True, verbose_name='Show on Homepage')),
                ('show_on_blog', models.BooleanField(default=True, verbose_name='Show on Blog Pages')),
                ('show_on_calculator_pages', models.BooleanField(default=True, verbose_name='Show on Calculator Pages')),
                ('show_on_user_pages', models.BooleanField(default=False, verbose_name='Show on User Pages')),
                ('show_on_static_pages', models.BooleanField(default=True, verbose_name='Show on Static Pages')),
                ('include_urls', models.TextField(blank=True, help_text='Comma-separated URL patterns to show ad (e.g., /math/, /finance/)', verbose_name='Include URLs')),
                ('exclude_urls', models.TextField(blank=True, help_text='Comma-separated URL patterns to hide ad (e.g., /user/, /admin/)', verbose_name='Exclude URLs')),
                ('show_on_desktop', models.BooleanField(default=True, verbose_name='Show on Desktop')),
                ('show_on_tablet', models.BooleanField(default=True, verbose_name='Show on Tablet')),
                ('show_on_mobile', models.BooleanField(default=True, verbose_name='Show on Mobile')),
                ('show_for_logged_in', models.BooleanField(default=True, verbose_name='Show for Logged-in Users')),
                ('show_for_anonymous', models.BooleanField(default=True, verbose_name='Show for Anonymous Users')),
                ('max_display_per_page', models.IntegerField(default=0, help_text='0 = unlimited', verbose_name='Max Displays per Page')),
                ('max_display_per_session', models.IntegerField(default=0, help_text='0 = unlimited', verbose_name='Max Displays per Session')),
                ('css_class', models.CharField(blank=True, help_text='Additional CSS classes for styling', max_length=100, verbose_name='CSS Class')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS styles for this ad unit', verbose_name='Custom CSS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this ad unit', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Ad Unit',
                'verbose_name_plural': 'Ad Units',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(max_length=100, verbose_name='Placement')),
                ('page_url', models.CharField(max_length=500, verbose_name='Page URL')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('is_mobile', models.BooleanField(default=False, verbose_name='Mobile Device')),
                ('displayed_at', models.DateTimeField(auto_now_add=True, verbose_name='Displayed At')),
                ('ad_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='google_adsense.adunit', verbose_name='Ad Unit')),
            ],
            options={
                'verbose_name': 'Ad Statistic',
                'verbose_name_plural': 'Ad Statistics',
                'ordering': ['-displayed_at'],
            },
        ),
    ]
