# Generated by Django 6.0.1 on 2026-01-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_adsense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adunit',
            name='exclude_blog_categories',
            field=models.TextField(blank=True, help_text='Comma-separated blog category slugs to exclude', verbose_name='Exclude Blog Categories'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_blog_tags',
            field=models.TextField(blank=True, help_text='Comma-separated blog tag slugs to exclude', verbose_name='Exclude Blog Tags'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_calculators',
            field=models.TextField(blank=True, help_text='Comma-separated calculator slugs to exclude (e.g., area-calculator, bmi-calculator)', verbose_name='Exclude Specific Calculators'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_from_admin',
            field=models.BooleanField(default=True, help_text='Do not show ads on /admin/ pages', verbose_name='Exclude from Admin Pages'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_from_blog_create',
            field=models.BooleanField(default=True, help_text='Do not show ads on blog post create/edit pages', verbose_name='Exclude from Blog Create/Edit'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_from_finance_calculators',
            field=models.BooleanField(default=False, help_text='Do not show ads on /finance/ pages', verbose_name='Exclude from Finance Calculators'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_from_health_calculators',
            field=models.BooleanField(default=False, help_text='Do not show ads on /health/ pages', verbose_name='Exclude from Health Calculators'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_from_login',
            field=models.BooleanField(default=True, help_text='Do not show ads on login/register pages', verbose_name='Exclude from Login Pages'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_from_math_calculators',
            field=models.BooleanField(default=False, help_text='Do not show ads on /math/ pages', verbose_name='Exclude from Math Calculators'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_from_other_calculators',
            field=models.BooleanField(default=False, help_text='Do not show ads on /other/ pages', verbose_name='Exclude from Other Calculators'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_from_privacy_pages',
            field=models.BooleanField(default=True, help_text='Do not show ads on privacy policy, terms, cookie policy pages', verbose_name='Exclude from Privacy/Terms Pages'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_from_user_dashboard',
            field=models.BooleanField(default=True, help_text='Do not show ads on user dashboard', verbose_name='Exclude from User Dashboard'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_from_user_profile',
            field=models.BooleanField(default=False, help_text='Do not show ads on user profile pages', verbose_name='Exclude from User Profiles'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_from_user_settings',
            field=models.BooleanField(default=True, help_text='Do not show ads on user settings pages', verbose_name='Exclude from User Settings'),
        ),
        migrations.AddField(
            model_name='adunit',
            name='exclude_placements',
            field=models.TextField(blank=True, help_text='Comma-separated placement names where this ad should NOT appear', verbose_name='Exclude from Placements'),
        ),
    ]
