# Generated by Django 6.0.1 on 2026-01-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed'),
        ),
    ]
