"""
Django settings for CalculatorDrive project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable in production: export SECRET_KEY='your-secret-key'
# Generate a new key: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-pzxmmuvl_uvl=hhxdl#&s+5pf7ykv31@kov5_86i0-9(v&rmp=')

# SECURITY WARNING: don't run with debug turned on in production!
# Use environment variable: export DEBUG=False
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Security: Set allowed hosts in production
# Use environment variable: export ALLOWED_HOSTS='yourdomain.com,www.yourdomain.com'
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'www.calculatordrive.com,calculatordrive.com').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'core',
    'Financial_Calculators',
    'Fitness_and_Health_Calculators',
    'Math_Calculators',
    'Other_Calculators',
    'blog',
    'user',
    'google_adsense',
    'django_extensions',

]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Language switching
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'user.middleware.UserSessionTrackingMiddleware',  # Track user sessions
    'user.middleware.EmailVerificationMiddleware',  # Email verification checks
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'calculator_drive.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'user.context_processors.notifications_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'calculator_drive.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('es', 'Español'),
    ('fr', 'Français'),
    ('de', 'Deutsch'),
    ('it', 'Italiano'),
    ('pt', 'Português'),
    ('ja', '日本語'),
    ('ru', 'Pусский'),
    ('ko', '한국어'),
    ('zh-hans', '中文 (简体)'),
    ('zh-hant', '中文 (繁體)'),
    ('ar', 'العربية'),
    ('bg', 'Български'),
    ('ca', 'Català'),
    ('nl', 'Nederlands'),
    ('el', 'Ελληνικά'),
    ('hi', 'हिन्दी'),
    ('id', 'Bahasa Indonesia'),
    ('ms', 'Bahasa Melayu'),
    ('pl', 'Polski'),
    ('sv', 'Svenska'),
    ('th', 'ภาษาไทย'),
    ('tr', 'Türkçe'),
    ('uk', 'Українська'),
    ('ur', 'اردو'),
    ('vi', 'Tiếng Việt'),
]

# RTL (Right-to-Left) languages
LANGUAGES_BIDI = ['ar', 'ur']

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For production: python manage.py collectstatic

# Media files (User uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Directory for user-uploaded files (blog images, avatars, etc.)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django-allauth configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'
ACCOUNT_ADAPTER = 'user.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'user.adapters.CustomSocialAccountAdapter'

# Allauth settings - using new format (django-allauth 0.65+)
# Signup fields - 'email*' (with asterisk) is required for mandatory email verification
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username', 'password1', 'password2']
# Login methods - allow login with email or username
ACCOUNT_LOGIN_METHODS = {'email', 'username'}

# Email settings
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Require email verification
ACCOUNT_UNIQUE_EMAIL = True  # Ensure unique emails

# Password settings
ACCOUNT_PASSWORD_MIN_LENGTH = 8
ACCOUNT_USERNAME_MIN_LENGTH = 3

# Session settings
ACCOUNT_SESSION_REMEMBER = True  # Remember user login

# Redirect URLs
ACCOUNT_LOGOUT_ON_GET = False
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_SIGNUP_REDIRECT_URL = '/'

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # Social accounts don't need email verification
SOCIALACCOUNT_EMAIL_REQUIRED = False

# Email Configuration
# Gmail SMTP Settings
# SECURITY NOTE: In production, use environment variables for EMAIL_HOST_PASSWORD
# Example: EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'samiullahkhialb@gmail.com'
EMAIL_HOST_PASSWORD = 'ifaw nvpq jnpq aihb'  # Gmail App Password
DEFAULT_FROM_EMAIL = 'noreply@CalculatorDrive.com'
SERVER_EMAIL = 'noreply@CalculatorDrive.com'

# TinyMCE Configuration for Blog Editor
TINYMCE_DEFAULT_CONFIG = {
    'mode': 'textareas',
    'theme': 'silver',
    'height': 300,
    'width': '100%',
    'plugins': [
        'advlist autolink lists link image charmap print preview anchor',
        'searchreplace visualblocks code fullscreen',
        'insertdatetime media table paste code help wordcount',
        'emoticons textcolor colorpicker',
    ],
    'toolbar': 'undo redo | formatselect | bold italic backcolor | \
               alignleft aligncenter alignright alignjustify | \
               bullist numlist outdent indent | link image emoticons | \
               code fullscreen',
    'formats': {
        'alignleft': {'selector': 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li', 'styles': {'textAlign': 'left'}},
        'aligncenter': {'selector': 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li', 'styles': {'textAlign': 'center'}},
        'alignright': {'selector': 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li', 'styles': {'textAlign': 'right'}},
        'alignjustify': {'selector': 'p,h1,h2,h3,h4,h5,h6,td,th,div,ul,ol,li', 'styles': {'textAlign': 'justify'}},
    },
}

TINYMCE_COMMENT_CONFIG = {
    'mode': 'textareas',
    'theme': 'silver',
    'height': 200,
    'width': '100%',
    'plugins': [
        'advlist autolink lists link image charmap print preview anchor',
        'searchreplace visualblocks code fullscreen',
        'insertdatetime media table paste code help wordcount',
    ],
    'toolbar': 'undo redo | formatselect | bold italic | alignleft aligncenter alignright | link image | code',
}

# Google AdSense Configuration
GOOGLE_ADSENSE_ENABLED = True  # Set to False to disable all ads globally
GOOGLE_ADSENSE_TRACK_DISPLAYS = False  # Set to True to track ad displays (requires AdStatistic model)

# Site Configuration for Sitemap
# Set your actual domain here (without http:// or https://)
# Example: 'yourdomain.com' or 'www.yourdomain.com'
SITE_URL = 'calculatordrive.com'  # Change this to your actual domain
SITE_PROTOCOL = 'https'  # Use 'https' for production, 'http' for development

# Cache Configuration
# Using simple in-memory cache for development
# For production, use Redis or Memcached
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'sitemap-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# ============================================================================
# SECURITY SETTINGS
# ============================================================================
# These settings should be configured for production deployment
# See SECURITY_REPORT.md for detailed security recommendations

# HTTPS/SSL Settings (for production)
# Set these to True when deploying with HTTPS
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'

# HTTP Strict Transport Security (HSTS)
# Only enable if your entire site is served over HTTPS
# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
SECURE_BROWSER_XSS_FILTER = True  # Enable browser's XSS filter
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking (already set by middleware, but explicit here)

# Session Security
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_AGE = 1209600  # 2 weeks (default)
SESSION_SAVE_EVERY_REQUEST = False  # Only save session if modified

# CSRF Settings
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF cookie
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF (default)
CSRF_COOKIE_AGE = 31449600  # 1 year (default)

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB (default)
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB (default)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000  # Prevent DoS via too many fields
DATA_UPLOAD_MAX_NUMBER_FILES = 100  # Maximum files per request

# Password Security (already configured above, but documented here)
# AUTH_PASSWORD_VALIDATORS are configured above
# ACCOUNT_PASSWORD_MIN_LENGTH = 8 (configured above)
