# Generated by Django 6.0.1 on 2026-01-10 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_language_profile_profile_privacy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_name', models.CharField(max_length=255, verbose_name='Calculator Name')),
                ('calculator_url', models.CharField(max_length=500, verbose_name='Calculator URL')),
                ('calculator_category', models.CharField(max_length=100, verbose_name='Category')),
                ('calculator_app', models.CharField(max_length=50, verbose_name='App')),
                ('calculator_description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_calculators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Calculator',
                'verbose_name_plural': 'Favorite Calculators',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'calculator_url')},
            },
        ),
    ]
